var g_resources = [
	"res/AboutScene_1.json",
	"res/CloseNormal.png",
	"res/CloseSelected.png",
	"res/favicon.ico",
	"res/MainMenuScene_1.json",
	"res/PlayGameScene_1.json",
	"res/SettingScene_1.json",
	"res/strings.json",
	"res/TutorialScene_1.json",

	"res/fonts/Marker Felt.ttf",

	"res/img/arrow.png",
	"res/img/bg_cave_1.png",
	"res/img/bg_side_1.png",
	"res/img/block_0.png",
	"res/img/block_1.png",
	"res/img/btn_about_n.png",
	"res/img/btn_about_p.png",
	"res/img/btn_back_n.png",
	"res/img/btn_back_p.png",
	"res/img/btn_continue_p.png",
	"res/img/btn_control_leftright_n.png",
	"res/img/btn_control_leftright_p.png",
	"res/img/btn_control_n.png",
	"res/img/btn_control_notjump_n.png",
	"res/img/btn_control_notjump_p.png",
	"res/img/btn_control_p.png",
	"res/img/btn_control_p1p2_n.png",
	"res/img/btn_control_p1p2_p.png",
	"res/img/btn_pause_n.png",
	"res/img/btn_pause_p.png",
	"res/img/btn_sound_n_off.png",
	"res/img/btn_sound_n_on.png",
	"res/img/btn_sound_p.png",
	"res/img/diamond.png",
	"res/img/fire.png",
	"res/img/fireball_single.png",
	"res/img/fire_1.png",
	"res/img/fire_2.png",
	"res/img/fire_light.png",
	"res/img/font_about.png",
	"res/img/font_control.png",
	"res/img/font_escape.png",
	"res/img/font_setting.png",
	"res/img/font_volcano.png",
	"res/img/gold.png",
	"res/img/icon_about.png",
	"res/img/icon_level.png",
	"res/img/icon_setting.png",
	"res/img/icon_start.png",
	"res/img/icon_super.png",
	"res/img/img_transparent.png",
	"res/img/kid.png",
	"res/img/mylogo.png",
	"res/img/red_bag.png",
	"res/img/title_bg.png",

	"res/music/empty.txt",

	"res/sound/sound_block_death.wav",
	"res/sound/sound_game_over.wav",
	"res/sound/sound_get_gold.wav",
	"res/sound/sound_jump.wav",
	"res/sound/sound_jump_down.wav",

	"res/sprite/fireball/FireBallAnimation.ExportJson",
	"res/sprite/fireball/FireBallAnimation0.plist",
	"res/sprite/fireball/FireBallAnimation0.png",

	"res/sprite/kid/KidAnimation.ExportJson",
	"res/sprite/kid/KidAnimation0.plist",
	"res/sprite/kid/KidAnimation0.png",

	"res/sprite/kidB/KidBAnimation.ExportJson",
	"res/sprite/kidB/KidBAnimation.plist",
	"res/sprite/kidB/KidBAnimation.png"
];